fragment AccueilParts on Accueil {
  __typename
  title
  description
  hero {
    __typename
    title
    subtitle
    about
  }
  sections {
    __typename
    histoireSubtitle
    missionsSubtitle
    projetsSubtitle
    equipeSubtitle
    soutienSubtitle
    ressourcesSubtitle
  }
}

fragment HistoireParts on Histoire {
  __typename
  year
  title
  description
  image
  order
}

fragment TeamParts on Team {
  __typename
  name
  role
  country
  location
  phone
  email
  photo
  bio
}

fragment MissionParts on Mission {
  __typename
  title
  description
  icon
  order
  active
}

fragment SupportParts on Support {
  __typename
  mainTitle
  whyTitle
  whyDescription
  impactListTitle
  impactItems {
    __typename
    text
  }
  impactMessage
  impactDescription
  howToTitle
  bankTransfer {
    __typename
    title
    description
    accountName
    iban
    bic
    communication
  }
  products {
    __typename
    title
    description
    item1
    item2
    item3
    contactName
    contactPhone
  }
  materialDonations {
    __typename
    title
    subtitle
    item1
    item2
    item3
    item4
  }
  membership {
    __typename
    title
    description
    benefit1
    benefit2
    benefit3
    benefit4
    contactEmail
  }
}

fragment ProjectParts on Project {
  __typename
  title
  year
  status
  description
  image
  location
  introTitle
  introText
  details {
    __typename
    beneficiaries
    budget
    goal
  }
  contentSections {
    __typename
    sectionTitle
    layout
    image
    content
  }
  conclusionText
  gallery
}

fragment BookParts on Book {
  __typename
  title
  author
  year
  isbn
  cover
  description
  category
  pages
  availability {
    __typename
    ebook
    ebookUrl
    print
    printUrl
    price
  }
  featured
}

fragment ContactParts on Contact {
  __typename
  country
  city
  address
  phone
  email
  hours {
    __typename
    weekdays
    weekend
  }
  notes
}
