//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  accueil: Accueil;
  accueilConnection: AccueilConnection;
  histoire: Histoire;
  histoireConnection: HistoireConnection;
  team: Team;
  teamConnection: TeamConnection;
  mission: Mission;
  missionConnection: MissionConnection;
  project: Project;
  projectConnection: ProjectConnection;
  book: Book;
  bookConnection: BookConnection;
  contact: Contact;
  contactConnection: ContactConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAccueilArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAccueilConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AccueilFilter>;
};


export type QueryHistoireArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHistoireConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HistoireFilter>;
};


export type QueryTeamArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTeamConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
};


export type QueryMissionArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMissionConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MissionFilter>;
};


export type QueryProjectArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
};


export type QueryBookArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBookConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BookFilter>;
};


export type QueryContactArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
};

export type DocumentFilter = {
  accueil?: InputMaybe<AccueilFilter>;
  histoire?: InputMaybe<HistoireFilter>;
  team?: InputMaybe<TeamFilter>;
  mission?: InputMaybe<MissionFilter>;
  project?: InputMaybe<ProjectFilter>;
  book?: InputMaybe<BookFilter>;
  contact?: InputMaybe<ContactFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Accueil | Histoire | Team | Mission | Project | Book | Contact | Folder;

export type AccueilHero = {
  __typename?: 'AccueilHero';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  about?: Maybe<Scalars['JSON']['output']>;
};

export type AccueilSections = {
  __typename?: 'AccueilSections';
  histoireSubtitle?: Maybe<Scalars['String']['output']>;
  missionsSubtitle?: Maybe<Scalars['String']['output']>;
  projetsSubtitle?: Maybe<Scalars['String']['output']>;
  equipeSubtitle?: Maybe<Scalars['String']['output']>;
  soutienSubtitle?: Maybe<Scalars['String']['output']>;
  ressourcesSubtitle?: Maybe<Scalars['String']['output']>;
};

export type Accueil = Node & Document & {
  __typename?: 'Accueil';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  hero?: Maybe<AccueilHero>;
  sections?: Maybe<AccueilSections>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type AccueilHeroFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  about?: InputMaybe<RichTextFilter>;
};

export type AccueilSectionsFilter = {
  histoireSubtitle?: InputMaybe<StringFilter>;
  missionsSubtitle?: InputMaybe<StringFilter>;
  projetsSubtitle?: InputMaybe<StringFilter>;
  equipeSubtitle?: InputMaybe<StringFilter>;
  soutienSubtitle?: InputMaybe<StringFilter>;
  ressourcesSubtitle?: InputMaybe<StringFilter>;
};

export type AccueilFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  hero?: InputMaybe<AccueilHeroFilter>;
  sections?: InputMaybe<AccueilSectionsFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type AccueilConnectionEdges = {
  __typename?: 'AccueilConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Accueil>;
};

export type AccueilConnection = Connection & {
  __typename?: 'AccueilConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AccueilConnectionEdges>>>;
};

export type Histoire = Node & Document & {
  __typename?: 'Histoire';
  year: Scalars['String']['output'];
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['JSON']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type HistoireFilter = {
  year?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<RichTextFilter>;
  image?: InputMaybe<ImageFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type HistoireConnectionEdges = {
  __typename?: 'HistoireConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Histoire>;
};

export type HistoireConnection = Connection & {
  __typename?: 'HistoireConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HistoireConnectionEdges>>>;
};

export type Team = Node & Document & {
  __typename?: 'Team';
  name: Scalars['String']['output'];
  role: Scalars['String']['output'];
  country: Scalars['String']['output'];
  location?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  photo?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TeamFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  country?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  photo?: InputMaybe<ImageFilter>;
  bio?: InputMaybe<RichTextFilter>;
};

export type TeamConnectionEdges = {
  __typename?: 'TeamConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Team>;
};

export type TeamConnection = Connection & {
  __typename?: 'TeamConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TeamConnectionEdges>>>;
};

export type Mission = Node & Document & {
  __typename?: 'Mission';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['JSON']['output']>;
  icon: Scalars['String']['output'];
  order: Scalars['Float']['output'];
  active?: Maybe<Scalars['Boolean']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type MissionFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<RichTextFilter>;
  icon?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  active?: InputMaybe<BooleanFilter>;
};

export type MissionConnectionEdges = {
  __typename?: 'MissionConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Mission>;
};

export type MissionConnection = Connection & {
  __typename?: 'MissionConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<MissionConnectionEdges>>>;
};

export type ProjectDetails = {
  __typename?: 'ProjectDetails';
  beneficiaries?: Maybe<Scalars['String']['output']>;
  budget?: Maybe<Scalars['String']['output']>;
  goal?: Maybe<Scalars['String']['output']>;
};

export type Project = Node & Document & {
  __typename?: 'Project';
  title: Scalars['String']['output'];
  year: Scalars['String']['output'];
  status: Scalars['String']['output'];
  description?: Maybe<Scalars['JSON']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  details?: Maybe<ProjectDetails>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ProjectDetailsFilter = {
  beneficiaries?: InputMaybe<StringFilter>;
  budget?: InputMaybe<StringFilter>;
  goal?: InputMaybe<StringFilter>;
};

export type ProjectFilter = {
  title?: InputMaybe<StringFilter>;
  year?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  description?: InputMaybe<RichTextFilter>;
  image?: InputMaybe<ImageFilter>;
  location?: InputMaybe<StringFilter>;
  details?: InputMaybe<ProjectDetailsFilter>;
};

export type ProjectConnectionEdges = {
  __typename?: 'ProjectConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Project>;
};

export type ProjectConnection = Connection & {
  __typename?: 'ProjectConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProjectConnectionEdges>>>;
};

export type BookAvailability = {
  __typename?: 'BookAvailability';
  ebook?: Maybe<Scalars['Boolean']['output']>;
  ebookUrl?: Maybe<Scalars['String']['output']>;
  print?: Maybe<Scalars['Boolean']['output']>;
  printUrl?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
};

export type Book = Node & Document & {
  __typename?: 'Book';
  title: Scalars['String']['output'];
  author?: Maybe<Scalars['String']['output']>;
  year?: Maybe<Scalars['String']['output']>;
  isbn?: Maybe<Scalars['String']['output']>;
  cover?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['JSON']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  pages?: Maybe<Scalars['Float']['output']>;
  availability?: Maybe<BookAvailability>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BookAvailabilityFilter = {
  ebook?: InputMaybe<BooleanFilter>;
  ebookUrl?: InputMaybe<StringFilter>;
  print?: InputMaybe<BooleanFilter>;
  printUrl?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
};

export type BookFilter = {
  title?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  year?: InputMaybe<StringFilter>;
  isbn?: InputMaybe<StringFilter>;
  cover?: InputMaybe<ImageFilter>;
  description?: InputMaybe<RichTextFilter>;
  category?: InputMaybe<StringFilter>;
  pages?: InputMaybe<NumberFilter>;
  availability?: InputMaybe<BookAvailabilityFilter>;
  featured?: InputMaybe<BooleanFilter>;
};

export type BookConnectionEdges = {
  __typename?: 'BookConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Book>;
};

export type BookConnection = Connection & {
  __typename?: 'BookConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BookConnectionEdges>>>;
};

export type ContactHours = {
  __typename?: 'ContactHours';
  weekdays?: Maybe<Scalars['String']['output']>;
  weekend?: Maybe<Scalars['String']['output']>;
};

export type Contact = Node & Document & {
  __typename?: 'Contact';
  country: Scalars['String']['output'];
  city?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  hours?: Maybe<ContactHours>;
  notes?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactHoursFilter = {
  weekdays?: InputMaybe<StringFilter>;
  weekend?: InputMaybe<StringFilter>;
};

export type ContactFilter = {
  country?: InputMaybe<StringFilter>;
  city?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  hours?: InputMaybe<ContactHoursFilter>;
  notes?: InputMaybe<RichTextFilter>;
};

export type ContactConnectionEdges = {
  __typename?: 'ContactConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contact>;
};

export type ContactConnection = Connection & {
  __typename?: 'ContactConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateAccueil: Accueil;
  createAccueil: Accueil;
  updateHistoire: Histoire;
  createHistoire: Histoire;
  updateTeam: Team;
  createTeam: Team;
  updateMission: Mission;
  createMission: Mission;
  updateProject: Project;
  createProject: Project;
  updateBook: Book;
  createBook: Book;
  updateContact: Contact;
  createContact: Contact;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateAccueilArgs = {
  relativePath: Scalars['String']['input'];
  params: AccueilMutation;
};


export type MutationCreateAccueilArgs = {
  relativePath: Scalars['String']['input'];
  params: AccueilMutation;
};


export type MutationUpdateHistoireArgs = {
  relativePath: Scalars['String']['input'];
  params: HistoireMutation;
};


export type MutationCreateHistoireArgs = {
  relativePath: Scalars['String']['input'];
  params: HistoireMutation;
};


export type MutationUpdateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};


export type MutationCreateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};


export type MutationUpdateMissionArgs = {
  relativePath: Scalars['String']['input'];
  params: MissionMutation;
};


export type MutationCreateMissionArgs = {
  relativePath: Scalars['String']['input'];
  params: MissionMutation;
};


export type MutationUpdateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationCreateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationUpdateBookArgs = {
  relativePath: Scalars['String']['input'];
  params: BookMutation;
};


export type MutationCreateBookArgs = {
  relativePath: Scalars['String']['input'];
  params: BookMutation;
};


export type MutationUpdateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationCreateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};

export type DocumentUpdateMutation = {
  accueil?: InputMaybe<AccueilMutation>;
  histoire?: InputMaybe<HistoireMutation>;
  team?: InputMaybe<TeamMutation>;
  mission?: InputMaybe<MissionMutation>;
  project?: InputMaybe<ProjectMutation>;
  book?: InputMaybe<BookMutation>;
  contact?: InputMaybe<ContactMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  accueil?: InputMaybe<AccueilMutation>;
  histoire?: InputMaybe<HistoireMutation>;
  team?: InputMaybe<TeamMutation>;
  mission?: InputMaybe<MissionMutation>;
  project?: InputMaybe<ProjectMutation>;
  book?: InputMaybe<BookMutation>;
  contact?: InputMaybe<ContactMutation>;
};

export type AccueilHeroMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  about?: InputMaybe<Scalars['JSON']['input']>;
};

export type AccueilSectionsMutation = {
  histoireSubtitle?: InputMaybe<Scalars['String']['input']>;
  missionsSubtitle?: InputMaybe<Scalars['String']['input']>;
  projetsSubtitle?: InputMaybe<Scalars['String']['input']>;
  equipeSubtitle?: InputMaybe<Scalars['String']['input']>;
  soutienSubtitle?: InputMaybe<Scalars['String']['input']>;
  ressourcesSubtitle?: InputMaybe<Scalars['String']['input']>;
};

export type AccueilMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  hero?: InputMaybe<AccueilHeroMutation>;
  sections?: InputMaybe<AccueilSectionsMutation>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type HistoireMutation = {
  year?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['JSON']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type TeamMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  country?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  photo?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['JSON']['input']>;
};

export type MissionMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['JSON']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  active?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ProjectDetailsMutation = {
  beneficiaries?: InputMaybe<Scalars['String']['input']>;
  budget?: InputMaybe<Scalars['String']['input']>;
  goal?: InputMaybe<Scalars['String']['input']>;
};

export type ProjectMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['JSON']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  details?: InputMaybe<ProjectDetailsMutation>;
};

export type BookAvailabilityMutation = {
  ebook?: InputMaybe<Scalars['Boolean']['input']>;
  ebookUrl?: InputMaybe<Scalars['String']['input']>;
  print?: InputMaybe<Scalars['Boolean']['input']>;
  printUrl?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
};

export type BookMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['String']['input']>;
  isbn?: InputMaybe<Scalars['String']['input']>;
  cover?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['JSON']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  pages?: InputMaybe<Scalars['Float']['input']>;
  availability?: InputMaybe<BookAvailabilityMutation>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ContactHoursMutation = {
  weekdays?: InputMaybe<Scalars['String']['input']>;
  weekend?: InputMaybe<Scalars['String']['input']>;
};

export type ContactMutation = {
  country?: InputMaybe<Scalars['String']['input']>;
  city?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  hours?: InputMaybe<ContactHoursMutation>;
  notes?: InputMaybe<Scalars['JSON']['input']>;
};

export type AccueilPartsFragment = { __typename: 'Accueil', title: string, description?: string | null, body?: any | null, hero?: { __typename: 'AccueilHero', title: string, subtitle?: string | null, about?: any | null } | null, sections?: { __typename: 'AccueilSections', histoireSubtitle?: string | null, missionsSubtitle?: string | null, projetsSubtitle?: string | null, equipeSubtitle?: string | null, soutienSubtitle?: string | null, ressourcesSubtitle?: string | null } | null };

export type HistoirePartsFragment = { __typename: 'Histoire', year: string, title: string, description?: any | null, image?: string | null, order?: number | null };

export type TeamPartsFragment = { __typename: 'Team', name: string, role: string, country: string, location?: string | null, phone?: string | null, email?: string | null, photo?: string | null, bio?: any | null };

export type MissionPartsFragment = { __typename: 'Mission', title: string, description?: any | null, icon: string, order: number, active?: boolean | null };

export type ProjectPartsFragment = { __typename: 'Project', title: string, year: string, status: string, description?: any | null, image?: string | null, location?: string | null, details?: { __typename: 'ProjectDetails', beneficiaries?: string | null, budget?: string | null, goal?: string | null } | null };

export type BookPartsFragment = { __typename: 'Book', title: string, author?: string | null, year?: string | null, isbn?: string | null, cover?: string | null, description?: any | null, category?: string | null, pages?: number | null, featured?: boolean | null, availability?: { __typename: 'BookAvailability', ebook?: boolean | null, ebookUrl?: string | null, print?: boolean | null, printUrl?: string | null, price?: string | null } | null };

export type ContactPartsFragment = { __typename: 'Contact', country: string, city?: string | null, address?: string | null, phone?: string | null, email?: string | null, notes?: any | null, hours?: { __typename: 'ContactHours', weekdays?: string | null, weekend?: string | null } | null };

export type AccueilQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AccueilQuery = { __typename?: 'Query', accueil: { __typename: 'Accueil', id: string, title: string, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'AccueilHero', title: string, subtitle?: string | null, about?: any | null } | null, sections?: { __typename: 'AccueilSections', histoireSubtitle?: string | null, missionsSubtitle?: string | null, projetsSubtitle?: string | null, equipeSubtitle?: string | null, soutienSubtitle?: string | null, ressourcesSubtitle?: string | null } | null } };

export type AccueilConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AccueilFilter>;
}>;


export type AccueilConnectionQuery = { __typename?: 'Query', accueilConnection: { __typename?: 'AccueilConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AccueilConnectionEdges', cursor: string, node?: { __typename: 'Accueil', id: string, title: string, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'AccueilHero', title: string, subtitle?: string | null, about?: any | null } | null, sections?: { __typename: 'AccueilSections', histoireSubtitle?: string | null, missionsSubtitle?: string | null, projetsSubtitle?: string | null, equipeSubtitle?: string | null, soutienSubtitle?: string | null, ressourcesSubtitle?: string | null } | null } | null } | null> | null } };

export type HistoireQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HistoireQuery = { __typename?: 'Query', histoire: { __typename: 'Histoire', id: string, year: string, title: string, description?: any | null, image?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type HistoireConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HistoireFilter>;
}>;


export type HistoireConnectionQuery = { __typename?: 'Query', histoireConnection: { __typename?: 'HistoireConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HistoireConnectionEdges', cursor: string, node?: { __typename: 'Histoire', id: string, year: string, title: string, description?: any | null, image?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TeamQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TeamQuery = { __typename?: 'Query', team: { __typename: 'Team', id: string, name: string, role: string, country: string, location?: string | null, phone?: string | null, email?: string | null, photo?: string | null, bio?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TeamConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
}>;


export type TeamConnectionQuery = { __typename?: 'Query', teamConnection: { __typename?: 'TeamConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TeamConnectionEdges', cursor: string, node?: { __typename: 'Team', id: string, name: string, role: string, country: string, location?: string | null, phone?: string | null, email?: string | null, photo?: string | null, bio?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type MissionQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type MissionQuery = { __typename?: 'Query', mission: { __typename: 'Mission', id: string, title: string, description?: any | null, icon: string, order: number, active?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type MissionConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MissionFilter>;
}>;


export type MissionConnectionQuery = { __typename?: 'Query', missionConnection: { __typename?: 'MissionConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'MissionConnectionEdges', cursor: string, node?: { __typename: 'Mission', id: string, title: string, description?: any | null, icon: string, order: number, active?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ProjectQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProjectQuery = { __typename?: 'Query', project: { __typename: 'Project', id: string, title: string, year: string, status: string, description?: any | null, image?: string | null, location?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, details?: { __typename: 'ProjectDetails', beneficiaries?: string | null, budget?: string | null, goal?: string | null } | null } };

export type ProjectConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
}>;


export type ProjectConnectionQuery = { __typename?: 'Query', projectConnection: { __typename?: 'ProjectConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProjectConnectionEdges', cursor: string, node?: { __typename: 'Project', id: string, title: string, year: string, status: string, description?: any | null, image?: string | null, location?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, details?: { __typename: 'ProjectDetails', beneficiaries?: string | null, budget?: string | null, goal?: string | null } | null } | null } | null> | null } };

export type BookQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BookQuery = { __typename?: 'Query', book: { __typename: 'Book', id: string, title: string, author?: string | null, year?: string | null, isbn?: string | null, cover?: string | null, description?: any | null, category?: string | null, pages?: number | null, featured?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, availability?: { __typename: 'BookAvailability', ebook?: boolean | null, ebookUrl?: string | null, print?: boolean | null, printUrl?: string | null, price?: string | null } | null } };

export type BookConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BookFilter>;
}>;


export type BookConnectionQuery = { __typename?: 'Query', bookConnection: { __typename?: 'BookConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BookConnectionEdges', cursor: string, node?: { __typename: 'Book', id: string, title: string, author?: string | null, year?: string | null, isbn?: string | null, cover?: string | null, description?: any | null, category?: string | null, pages?: number | null, featured?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, availability?: { __typename: 'BookAvailability', ebook?: boolean | null, ebookUrl?: string | null, print?: boolean | null, printUrl?: string | null, price?: string | null } | null } | null } | null> | null } };

export type ContactQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactQuery = { __typename?: 'Query', contact: { __typename: 'Contact', id: string, country: string, city?: string | null, address?: string | null, phone?: string | null, email?: string | null, notes?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hours?: { __typename: 'ContactHours', weekdays?: string | null, weekend?: string | null } | null } };

export type ContactConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
}>;


export type ContactConnectionQuery = { __typename?: 'Query', contactConnection: { __typename?: 'ContactConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactConnectionEdges', cursor: string, node?: { __typename: 'Contact', id: string, country: string, city?: string | null, address?: string | null, phone?: string | null, email?: string | null, notes?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hours?: { __typename: 'ContactHours', weekdays?: string | null, weekend?: string | null } | null } | null } | null> | null } };

export const AccueilPartsFragmentDoc = gql`
    fragment AccueilParts on Accueil {
  __typename
  title
  description
  hero {
    __typename
    title
    subtitle
    about
  }
  sections {
    __typename
    histoireSubtitle
    missionsSubtitle
    projetsSubtitle
    equipeSubtitle
    soutienSubtitle
    ressourcesSubtitle
  }
  body
}
    `;
export const HistoirePartsFragmentDoc = gql`
    fragment HistoireParts on Histoire {
  __typename
  year
  title
  description
  image
  order
}
    `;
export const TeamPartsFragmentDoc = gql`
    fragment TeamParts on Team {
  __typename
  name
  role
  country
  location
  phone
  email
  photo
  bio
}
    `;
export const MissionPartsFragmentDoc = gql`
    fragment MissionParts on Mission {
  __typename
  title
  description
  icon
  order
  active
}
    `;
export const ProjectPartsFragmentDoc = gql`
    fragment ProjectParts on Project {
  __typename
  title
  year
  status
  description
  image
  location
  details {
    __typename
    beneficiaries
    budget
    goal
  }
}
    `;
export const BookPartsFragmentDoc = gql`
    fragment BookParts on Book {
  __typename
  title
  author
  year
  isbn
  cover
  description
  category
  pages
  availability {
    __typename
    ebook
    ebookUrl
    print
    printUrl
    price
  }
  featured
}
    `;
export const ContactPartsFragmentDoc = gql`
    fragment ContactParts on Contact {
  __typename
  country
  city
  address
  phone
  email
  hours {
    __typename
    weekdays
    weekend
  }
  notes
}
    `;
export const AccueilDocument = gql`
    query accueil($relativePath: String!) {
  accueil(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AccueilParts
  }
}
    ${AccueilPartsFragmentDoc}`;
export const AccueilConnectionDocument = gql`
    query accueilConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AccueilFilter) {
  accueilConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AccueilParts
      }
    }
  }
}
    ${AccueilPartsFragmentDoc}`;
export const HistoireDocument = gql`
    query histoire($relativePath: String!) {
  histoire(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HistoireParts
  }
}
    ${HistoirePartsFragmentDoc}`;
export const HistoireConnectionDocument = gql`
    query histoireConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HistoireFilter) {
  histoireConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HistoireParts
      }
    }
  }
}
    ${HistoirePartsFragmentDoc}`;
export const TeamDocument = gql`
    query team($relativePath: String!) {
  team(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TeamParts
  }
}
    ${TeamPartsFragmentDoc}`;
export const TeamConnectionDocument = gql`
    query teamConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TeamFilter) {
  teamConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TeamParts
      }
    }
  }
}
    ${TeamPartsFragmentDoc}`;
export const MissionDocument = gql`
    query mission($relativePath: String!) {
  mission(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...MissionParts
  }
}
    ${MissionPartsFragmentDoc}`;
export const MissionConnectionDocument = gql`
    query missionConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: MissionFilter) {
  missionConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...MissionParts
      }
    }
  }
}
    ${MissionPartsFragmentDoc}`;
export const ProjectDocument = gql`
    query project($relativePath: String!) {
  project(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProjectParts
  }
}
    ${ProjectPartsFragmentDoc}`;
export const ProjectConnectionDocument = gql`
    query projectConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProjectFilter) {
  projectConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProjectParts
      }
    }
  }
}
    ${ProjectPartsFragmentDoc}`;
export const BookDocument = gql`
    query book($relativePath: String!) {
  book(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BookParts
  }
}
    ${BookPartsFragmentDoc}`;
export const BookConnectionDocument = gql`
    query bookConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BookFilter) {
  bookConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BookParts
      }
    }
  }
}
    ${BookPartsFragmentDoc}`;
export const ContactDocument = gql`
    query contact($relativePath: String!) {
  contact(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactParts
  }
}
    ${ContactPartsFragmentDoc}`;
export const ContactConnectionDocument = gql`
    query contactConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactFilter) {
  contactConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactParts
      }
    }
  }
}
    ${ContactPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      accueil(variables: AccueilQueryVariables, options?: C): Promise<{data: AccueilQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AccueilQueryVariables, query: string}> {
        return requester<{data: AccueilQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AccueilQueryVariables, query: string}, AccueilQueryVariables>(AccueilDocument, variables, options);
      },
    accueilConnection(variables?: AccueilConnectionQueryVariables, options?: C): Promise<{data: AccueilConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AccueilConnectionQueryVariables, query: string}> {
        return requester<{data: AccueilConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AccueilConnectionQueryVariables, query: string}, AccueilConnectionQueryVariables>(AccueilConnectionDocument, variables, options);
      },
    histoire(variables: HistoireQueryVariables, options?: C): Promise<{data: HistoireQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HistoireQueryVariables, query: string}> {
        return requester<{data: HistoireQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HistoireQueryVariables, query: string}, HistoireQueryVariables>(HistoireDocument, variables, options);
      },
    histoireConnection(variables?: HistoireConnectionQueryVariables, options?: C): Promise<{data: HistoireConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HistoireConnectionQueryVariables, query: string}> {
        return requester<{data: HistoireConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HistoireConnectionQueryVariables, query: string}, HistoireConnectionQueryVariables>(HistoireConnectionDocument, variables, options);
      },
    team(variables: TeamQueryVariables, options?: C): Promise<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}> {
        return requester<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}, TeamQueryVariables>(TeamDocument, variables, options);
      },
    teamConnection(variables?: TeamConnectionQueryVariables, options?: C): Promise<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}> {
        return requester<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}, TeamConnectionQueryVariables>(TeamConnectionDocument, variables, options);
      },
    mission(variables: MissionQueryVariables, options?: C): Promise<{data: MissionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MissionQueryVariables, query: string}> {
        return requester<{data: MissionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MissionQueryVariables, query: string}, MissionQueryVariables>(MissionDocument, variables, options);
      },
    missionConnection(variables?: MissionConnectionQueryVariables, options?: C): Promise<{data: MissionConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MissionConnectionQueryVariables, query: string}> {
        return requester<{data: MissionConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MissionConnectionQueryVariables, query: string}, MissionConnectionQueryVariables>(MissionConnectionDocument, variables, options);
      },
    project(variables: ProjectQueryVariables, options?: C): Promise<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}> {
        return requester<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}, ProjectQueryVariables>(ProjectDocument, variables, options);
      },
    projectConnection(variables?: ProjectConnectionQueryVariables, options?: C): Promise<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}> {
        return requester<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}, ProjectConnectionQueryVariables>(ProjectConnectionDocument, variables, options);
      },
    book(variables: BookQueryVariables, options?: C): Promise<{data: BookQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookQueryVariables, query: string}> {
        return requester<{data: BookQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookQueryVariables, query: string}, BookQueryVariables>(BookDocument, variables, options);
      },
    bookConnection(variables?: BookConnectionQueryVariables, options?: C): Promise<{data: BookConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookConnectionQueryVariables, query: string}> {
        return requester<{data: BookConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BookConnectionQueryVariables, query: string}, BookConnectionQueryVariables>(BookConnectionDocument, variables, options);
      },
    contact(variables: ContactQueryVariables, options?: C): Promise<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}> {
        return requester<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}, ContactQueryVariables>(ContactDocument, variables, options);
      },
    contactConnection(variables?: ContactConnectionQueryVariables, options?: C): Promise<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}> {
        return requester<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}, ContactConnectionQueryVariables>(ContactConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  